# Generated by Django 2.0.2 on 2018-02-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='education',
            name='gpa',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='education',
            name='major',
            field=models.CharField(max_length=128),
        ),
    ]
